name: Unit Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsndfile1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Test package import
      run: |
        python -c "import AFX; print('AFX package imported successfully')"

    - name: Run core feature tests (must pass)
      run: |
        python -m pytest tests/test_harmonic_features.py tests/test_cepstral_features.py tests/test_frequency_domain.py tests/test_time_domain.py tests/test_pitch.py tests/test_utils.py tests/test_config_io.py -v --tb=short

    - name: Run all tests (informational)
      run: |
        python -m pytest tests/ -v --tb=short || echo "Some tests failed, but this is expected for pre-existing issues"
      continue-on-error: true